### ISSUE TITLE
Laborejo

### ISSUE THREAD

**Issue by diovudau** [kreincke/mwm.ltx#1]
Laborejo-Autor hier.

Kapitel 3.4.12  beschreibt mein Programm. Hier einige Richtigstellungen:

m September 2019, laut Kapitelfußnote,, stand als Version auf meiner Webseite noch "2.0: nicht released". 
Die Version 0.8 in Ubuntu ist ein Prototyp von ca. 2012. Ich weiß auch nicht warum das dort als Paket angeboten wird. Es ist ein Wunder, dass es überhaupt gestartet ist, nach all der vergangen Zeit.

Dementsprechend ist die nachfolgende Betrachtung auf Seite 76 auch hinfällig.

Das englische Handbuch endet nach wie vor in einer "Hello World" Seite. Das Deutsche war und ist zumindest schon ein guter Anfang (auch auf der Webseite verlinkt). 

Aus zuälligen Gründen ist die Einschätzung als Eignung dennoch beim richtigen Fazit gelandet. Ich selbst schreibe für eigene musikwissenschaftlichen Artikel (bzw. eher Musiktheoretische bei mir) direkt Lilypond. Laborejo wird höchstens für einen Geschwindigkeitszuwachs bei der Eingabe sorgen.

**Comment by kreincke** [comment]
Danke für den angenehmen Gedankenaustauch per mail. Die Version 1.5 mit einem geupdateten Laborejo-Kapitel ist jetzt online.
